#!/usr/bin/env python3
"""Convert the pinned Falcon NTSC 1.02 frame-data dump to compact C tables."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any


EXPECTED_CANONICAL_SHA256 = (
    "42bb4ecefb33e87dc978482ecdb7b1f93ff12ca090e870431fff913480601356"
)
EXTRACTOR_REVISION = "0b12c5cb988da3fb9b67630b1d8347e12cd91528"
DAT_READER_REVISION = "d4e6074aa26f388fccc7fe8e825761cf1c1bc7b0"
SOURCE_DAT_SHA256 = (
    "4cf61a52737d464df9298fd15573345fb3b9a15c79ab47dce4fd2e3e707917af"
)
SOURCE_ANIMATION_DAT_SHA256 = (
    "a9a0ccc2382a2f02d5423675469719488540dd119a14577712c97348f70e1c1a"
)

MOVE_KEYS = (
    "jab1", "jab2", "jab3", "rapidjabs_start", "rapidjabs_loop",
    "rapidjabs_end", "dashattack", "ftilt_h", "ftilt_mh", "ftilt_m",
    "ftilt_ml", "ftilt_l", "utilt", "dtilt", "fsmash_h", "fsmash_mh",
    "fsmash_m", "fsmash_ml", "fsmash_l", "usmash", "dsmash", "nair",
    "fair", "bair", "uair", "dair", "grab", "dashgrab", "pummel",
    "fthrow", "bthrow", "uthrow", "dthrow", "0x12d", "0x12e", "0x12f",
    "0x130", "0x131", "0x132", "0x133", "0x134", "0x135", "0x136",
    "0x137", "0x138", "0x139", "0x13a", "0x13b", "0x13c", "0x13d",
)

ELEMENTS = {
    "empty": "PF_M4_REFERENCE_HIT_EMPTY",
    "normal": "PF_M4_REFERENCE_HIT_NORMAL",
    "fire": "PF_M4_REFERENCE_HIT_FIRE",
    "electric": "PF_M4_REFERENCE_HIT_ELECTRIC",
    "grab": "PF_M4_REFERENCE_HIT_GRAB",
}


def canonical_sha256(data: dict[str, Any]) -> str:
    encoded = json.dumps(
        data, sort_keys=True, separators=(",", ":")
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def u16(value: Any) -> int:
    return 0 if value is None else int(value)


def generate(data: dict[str, Any]) -> str:
    phases: list[tuple[int, int, int]] = []
    effects: list[dict[str, Any]] = []
    throws: list[dict[str, Any]] = []
    moves: list[dict[str, int]] = []

    if tuple(data) != MOVE_KEYS:
        raise ValueError("unexpected move order or incomplete Falcon table")

    for key in MOVE_KEYS:
        move = data[key]
        if move is None:
            moves.append({"present": 0})
            continue

        phase_offset = len(phases)
        effect_offset = len(effects)
        move_effects = move.get("hitboxes", [])
        if len(move_effects) > 16:
            raise ValueError(f"{key}: too many hit effects")
        effects.extend(move_effects)
        for phase in move.get("hitFrames", []):
            mask = 0
            for effect_index in phase["hitboxes"]:
                if not 0 <= int(effect_index) < len(move_effects):
                    raise ValueError(f"{key}: invalid hit-effect index")
                mask |= 1 << int(effect_index)
            phases.append((int(phase["start"]), int(phase["end"]), mask))

        throw_index = 0xFFFF
        if "throw" in move:
            throw_index = len(throws)
            throws.append(move["throw"])
        moves.append(
            {
                "present": 1,
                "subaction": int(move["subactionIndex"]),
                "total": int(move["totalFrames"]),
                "iasa": u16(move.get("iasa")),
                "charge": u16(move.get("chargeFrame")),
                "autocancel_before": u16(move.get("autoCancelBefore")),
                "autocancel_after": u16(move.get("autoCancelAfter")),
                "landing": u16(move.get("landingLag")),
                "l_cancelled": u16(move.get("lcancelledLandingLag")),
                "phase_offset": phase_offset,
                "effect_offset": effect_offset,
                "throw_index": throw_index,
                "phase_count": len(move.get("hitFrames", [])),
                "effect_count": len(move_effects),
            }
        )

    lines = [
        "/* Generated by tools/import_ssbm_falcon_frame_data.py; do not edit. */",
        f"/* canonical source SHA-256: {EXPECTED_CANONICAL_SHA256} */",
        f"/* extractor revision: {EXTRACTOR_REVISION} */",
        f"/* DAT reader revision: {DAT_READER_REVISION} */",
        f"/* PlCa.dat SHA-256: {SOURCE_DAT_SHA256} */",
        f"/* PlCaAJ.dat SHA-256: {SOURCE_ANIMATION_DAT_SHA256} */",
        "",
        "static const uint8_t pf_m4_falcon_source_sha256[32] = {",
        "    " + ", ".join(
            f"UINT8_C(0x{EXPECTED_CANONICAL_SHA256[index:index + 2]})"
            for index in range(0, len(EXPECTED_CANONICAL_SHA256), 2)
        ),
        "};",
        "",
        "static const pf_m4_reference_hit_phase pf_m4_falcon_hit_phases[] = {",
    ]
    lines.extend(
        f"    {{ UINT16_C({start}), UINT16_C({end}), UINT16_C({mask}), UINT16_C(0) }},"
        for start, end, mask in phases
    )
    lines.extend(("};", "", "static const pf_m4_reference_hit_effect pf_m4_falcon_hit_effects[] = {"))
    for effect in effects:
        element = ELEMENTS[str(effect["element"])]
        lines.append(
            "    { "
            f"UINT16_C({int(effect['angle'])}), "
            f"UINT16_C({int(effect['kbGrowth'])}), "
            f"UINT16_C({int(effect['weightDepKb'])}), "
            f"UINT16_C({int(effect['baseKb'])}), "
            f"UINT8_C({int(effect['damage'])}), "
            f"UINT8_C({int(effect['shieldDamage'])}), "
            f"UINT8_C({int(effect['hitboxInteraction'])}), "
            f"(uint8_t){element}, "
            f"UINT8_C({1 if effect['hitGrounded'] else 0}), "
            f"UINT8_C({1 if effect['hitAirborne'] else 0}), "
            "{ UINT8_C(0), UINT8_C(0) } },"
        )
    lines.extend(("};", "", "static const pf_m4_reference_throw pf_m4_falcon_throws[] = {"))
    for throw in throws:
        lines.append(
            "    { "
            f"UINT16_C({int(throw['angle'])}), "
            f"UINT16_C({int(throw['kbGrowth'])}), "
            f"UINT16_C({int(throw['weightDepKb'])}), "
            f"UINT16_C({int(throw['baseKb'])}), "
            f"UINT8_C({int(throw['damage'])}), "
            f"UINT8_C({int(throw['element'])}), "
            "{ UINT8_C(0), UINT8_C(0) } },"
        )
    lines.extend(("};", "", "static const pf_m4_reference_move pf_m4_falcon_moves[PF_M4_FALCON_MOVE_COUNT] = {"))
    for move in moves:
        if move["present"] == 0:
            lines.append("    { 0 },")
            continue
        lines.append(
            "    { "
            f"UINT16_C({move['subaction']}), UINT16_C({move['total']}), "
            f"UINT16_C({move['iasa']}), UINT16_C({move['charge']}), "
            f"UINT16_C({move['autocancel_before']}), "
            f"UINT16_C({move['autocancel_after']}), "
            f"UINT16_C({move['landing']}), UINT16_C({move['l_cancelled']}), "
            f"UINT16_C({move['phase_offset']}), UINT16_C({move['effect_offset']}), "
            f"UINT16_C({move['throw_index']}), UINT8_C({move['phase_count']}), "
            f"UINT8_C({move['effect_count']}), UINT8_C(1), UINT8_C(0) }},"
        )
    lines.extend(("};", ""))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    data = json.loads(args.source.read_text(encoding="utf-8"))
    digest = canonical_sha256(data)
    if digest != EXPECTED_CANONICAL_SHA256:
        raise SystemExit(
            f"unexpected Falcon frame-data SHA-256: {digest}"
        )
    output = generate(data)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8", newline="\n")
    print(
        "ssbm-falcon-frame-data=pass "
        f"moves={len(MOVE_KEYS)} source_sha256={digest} output={args.output}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
