#!/usr/bin/env python3
"""Generate common NTSC 1.02 fighter data from the owner-supplied PlCo.dat."""

from __future__ import annotations

import argparse
import hashlib
import math
from pathlib import Path
import struct

from ssbm_dat import ft_common_data


SOURCE_COMMON_DAT_SHA256 = (
    "63841336337eb5a7366b06ccc60ea4bd37c3604ab56e19939d78b9aa9cdd234c"
)
DECOMP_REVISION = "9509dc04406fb2028bfab01243841ba4787c0fb7"
FT_COMMON_DATA_SIZE = 0x818
MELEE_X_TO_SIM_Q16 = 65536.0 * 12.0 / 115.0
MELEE_Y_TO_SIM_Q16 = 65536.0 * 11.0 / 62.0


def q16(value: float) -> int:
    return round(value * 65536.0)


def generate(raw: bytes) -> str:
    data, pointers = ft_common_data(raw)
    common_offset = pointers[0]
    if common_offset + FT_COMMON_DATA_SIZE > len(data):
        raise ValueError("truncated ftCommonData object")
    raw_common = data[common_offset : common_offset + FT_COMMON_DATA_SIZE]
    raw_words = struct.unpack(f">{FT_COMMON_DATA_SIZE // 4}I", raw_common)

    def f32(offset: int) -> float:
        return struct.unpack_from(">f", raw_common, offset)[0]

    def i32(offset: int) -> int:
        return struct.unpack_from(">i", raw_common, offset)[0]

    tilt_x = f32(0x008)
    tilt_y = f32(0x00C)
    if tilt_x != tilt_y or not 0.0 < tilt_x < 1.0:
        raise ValueError("unexpected asymmetric common stick-tilt threshold")
    sdi_threshold = f32(0x4B0)
    sdi_window = i32(0x4B4)
    if not 0.0 < sdi_threshold <= 1.0:
        raise ValueError("invalid common SDI stick threshold")
    if sdi_window <= 0 or sdi_window > 0xFFFF:
        raise ValueError("common SDI window does not fit uint16_t")

    attributes = {
        "stick_tilt_threshold": round(tilt_x * 32767.0),
        "hitstun_per_knockback_q16": q16(f32(0x154)),
        "launch_speed_x_per_knockback_q16": round(
            f32(0x100) * MELEE_X_TO_SIM_Q16
        ),
        "launch_speed_y_per_knockback_q16": round(
            f32(0x100) * MELEE_Y_TO_SIM_Q16
        ),
        "di_max_angle_radians_q30": round(
            math.radians(f32(0x1A8)) * float(1 << 30)
        ),
        "ground_knockback_decay_scale_q16": q16(f32(0x200)),
        # Knockback decay is a magnitude subtraction in Melee coordinates.
        # Keep the source scalar: per-axis conversion before the vector
        # operation changes the angle under this project's anisotropic scale.
        "air_knockback_decay_q16": q16(f32(0x204)),
        "sdi_stick_threshold": round(sdi_threshold * 32767.0),
        "sdi_stick_window_ticks": sdi_window,
        "sdi_distance_x_q16": round(f32(0x4B8) * MELEE_X_TO_SIM_Q16),
        "sdi_distance_y_q16": round(f32(0x4B8) * MELEE_Y_TO_SIM_Q16),
        "asdi_distance_x_q16": round(f32(0x4BC) * MELEE_X_TO_SIM_Q16),
        "asdi_distance_y_q16": round(f32(0x4BC) * MELEE_Y_TO_SIM_Q16),
        "shield_sdi_scale_q16": q16(f32(0x4C0)),
    }

    lines = [
        "/* Generated by tools/import_ssbm_common_data.py; do not edit. */",
        f"/* PlCo.dat SHA-256: {SOURCE_COMMON_DAT_SHA256} */",
        f"/* doldecomp/melee revision: {DECOMP_REVISION} */",
        "",
        "static const uint8_t pf_m4_ssbm_common_source_sha256[32] = {",
        "    "
        + ", ".join(
            f"UINT8_C(0x{SOURCE_COMMON_DAT_SHA256[index:index + 2]})"
            for index in range(0, 64, 2)
        ),
        "};",
        "",
        "static const uint32_t",
        "pf_m4_ssbm_common_raw_words[PF_M4_SSBM_COMMON_RAW_WORD_COUNT] = {",
    ]
    lines.extend(
        "    "
        + ", ".join(
            f"UINT32_C(0x{word:08x})" for word in raw_words[index : index + 6]
        )
        + ","
        for index in range(0, len(raw_words), 6)
    )
    lines.extend(
        [
            "};",
            "",
            "static const pf_m4_ssbm_damage_response_attributes",
            "pf_m4_ssbm_damage_response_attribute_data = {",
            f"    INT32_C({attributes['hitstun_per_knockback_q16']}),",
            f"    INT32_C({attributes['launch_speed_x_per_knockback_q16']}),",
            f"    INT32_C({attributes['launch_speed_y_per_knockback_q16']}),",
            f"    INT32_C({attributes['di_max_angle_radians_q30']}),",
            f"    INT32_C({attributes['ground_knockback_decay_scale_q16']}),",
            f"    INT32_C({attributes['air_knockback_decay_q16']}),",
            f"    INT32_C({attributes['sdi_distance_x_q16']}),",
            f"    INT32_C({attributes['sdi_distance_y_q16']}),",
            f"    INT32_C({attributes['asdi_distance_x_q16']}),",
            f"    INT32_C({attributes['asdi_distance_y_q16']}),",
            f"    INT32_C({attributes['shield_sdi_scale_q16']}),",
            f"    UINT16_C({attributes['stick_tilt_threshold']}),",
            f"    UINT16_C({attributes['sdi_stick_threshold']}),",
            f"    UINT16_C({attributes['sdi_stick_window_ticks']}),",
            "    UINT16_C(0),",
            "};",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("common_dat", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    raw = args.common_dat.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    if digest != SOURCE_COMMON_DAT_SHA256:
        raise SystemExit(f"unexpected PlCo.dat SHA-256: {digest}")
    generated = generate(raw)
    if args.check:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != generated:
            raise SystemExit(f"stale generated common data: {args.output}")
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(generated, encoding="utf-8", newline="\n")
    print(
        "ssbm-common-data=pass "
        f"raw_words={FT_COMMON_DATA_SIZE // 4} "
        f"source_sha256={digest} output={args.output}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
